#!/usr/bin/env python3
"""Rename safe item handlers one at a time with verify-and-revert.

This is the conservative workflow:
- find candidates that look safe to rename
- apply exactly one rename
- build and verify
- keep the rename if it matches, otherwise restore touched files
- continue to the next candidate

Examples:
  python3 tools/iterative_safe_item_handler_rename.py herb --effect use --dry-run
  python3 tools/iterative_safe_item_handler_rename.py herb --effect use
  python3 tools/iterative_safe_item_handler_rename.py herb --effect use --limit 2
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from item_pipeline import build_item_infos, parse_category_arg, is_raw_handler, ROOT, BANK03_PATH
from item_rename_candidates import build_addr_to_label, gather_direct_call_counts, raw_to_entry_addr
from safe_item_handler_rename import update_table_entry, rename_label_and_references, ASM_PATHS, LABEL_LINE_RE


VALID_SYMBOL_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


@dataclass
class PlannedRename:
    item_const: str
    item_suffix: str
    old_handler: str
    lifted_symbol: str
    new_symbol: str
    path: Path
    line_no: int


def build_label_locations() -> dict[str, tuple[Path, int, str]]:
    locations: dict[str, tuple[Path, int, str]] = {}
    for path in ASM_PATHS:
        lines = path.read_text(encoding="utf-8").splitlines()
        for idx, line in enumerate(lines, 1):
            match = LABEL_LINE_RE.match(line)
            if match:
                locations[match.group("label")] = (path, idx, match.group("label"))
    return locations


def plan_renames(category: str, effect: str) -> tuple[int, list[PlannedRename], list[str]]:
    category_code = parse_category_arg(category)
    infos = [info for info in build_item_infos() if info.category_code == category_code]
    if not infos:
        raise SystemExit(f"no items found for category ${category_code:02X}")

    handler_attr = "use_handler" if effect == "use" else "throw_handler"
    suffix = "UseEffect" if effect == "use" else "ThrowEffect"
    handler_counts = Counter(getattr(info, handler_attr) for info in infos)
    addr_to_label = build_addr_to_label()
    direct_call_counts = gather_direct_call_counts()
    label_locations = build_label_locations()

    planned: list[PlannedRename] = []
    skipped: list[str] = []
    for info in infos:
        handler = getattr(info, handler_attr)
        if handler == "UnusedItemUseEffect":
            continue
        if handler_counts[handler] != 1:
            skipped.append(f"{info.const_name}: shared handler {handler}")
            continue

        lifted_symbol = None
        if is_raw_handler(handler):
            entry_addr = raw_to_entry_addr(handler)
            if entry_addr is not None:
                lifted_symbol = addr_to_label.get(entry_addr)
        else:
            lifted_symbol = handler

        caller_keys = [k for k in (handler, lifted_symbol) if k]
        direct_callers = sum(direct_call_counts.get(key, 0) for key in caller_keys)
        if direct_callers != 0:
            skipped.append(f"{info.const_name}: extra direct callers {direct_callers}")
            continue
        if not lifted_symbol or lifted_symbol not in label_locations:
            skipped.append(f"{info.const_name}: no standalone label for {handler}")
            continue

        new_symbol = f"{info.const_name.removeprefix('Item_')}{suffix}"
        if not VALID_SYMBOL_RE.fullmatch(new_symbol):
            skipped.append(f"{info.const_name}: autogenerated symbol would be invalid ({new_symbol})")
            continue
        if handler == new_symbol or lifted_symbol == new_symbol:
            continue

        path, line_no, _ = label_locations[lifted_symbol]
        planned.append(
            PlannedRename(
                item_const=info.const_name,
                item_suffix=info.const_name.removeprefix("Item_"),
                old_handler=handler,
                lifted_symbol=lifted_symbol,
                new_symbol=new_symbol,
                path=path,
                line_no=line_no,
            )
        )
    return category_code, planned, skipped


def verify() -> None:
    subprocess.run(
        "make -B -j PYTHON=.venv/bin/python && shasum -c shiren.sha1",
        shell=True,
        check=True,
        cwd=ROOT,
    )


def snapshot(paths: list[Path]) -> dict[Path, str]:
    return {path: path.read_text(encoding="utf-8") for path in paths}


def restore(saved: dict[Path, str]) -> None:
    for path, text in saved.items():
        path.write_text(text, encoding="utf-8")


def verify_clean_tree() -> None:
    subprocess.run(
        "make -B -j PYTHON=.venv/bin/python && shasum -c shiren.sha1",
        shell=True,
        check=True,
        cwd=ROOT,
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("category", help="category code or name, e.g. herb, jar, 00, 0B")
    parser.add_argument("--effect", choices=("use", "throw"), default="use")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--limit", type=int, default=0, help="stop after this many successful renames (0 = no limit)")
    parser.add_argument("--stop-on-fail", action="store_true")
    args = parser.parse_args(argv)

    category_code, planned, skipped = plan_renames(args.category, args.effect)
    print(f"category ${category_code:02X}, effect={args.effect}")
    print(f"planned renames: {len(planned)}")
    for item in planned:
        print(f"  {item.item_const}: {item.lifted_symbol} -> {item.new_symbol}")
    if skipped:
        print(f"skipped: {len(skipped)}")
        for line in skipped:
            print(f"  {line}")

    if args.dry_run:
        print("dry run: no files written")
        return 0

    successes: list[str] = []
    failures: list[str] = []
    for item in planned:
        saved = snapshot([BANK03_PATH, item.path])
        print(f"apply: {item.item_const}: {item.lifted_symbol} -> {item.new_symbol}")
        update_table_entry(item.item_suffix, args.effect, item.new_symbol, dry_run=False)
        rename_label_and_references(item.path, item.line_no, item.lifted_symbol, item.new_symbol, dry_run=False)
        try:
            verify()
        except subprocess.CalledProcessError:
            restore(saved)
            verify_clean_tree()
            failures.append(item.item_const)
            print(f"revert: {item.item_const} (verify failed)")
            if args.stop_on_fail:
                break
            continue
        successes.append(item.item_const)
        print(f"keep: {item.item_const}")
        if args.limit and len(successes) >= args.limit:
            break

    print(f"successful renames: {len(successes)}")
    for item in successes:
        print(f"  {item}")
    if failures:
        print(f"failed renames: {len(failures)}")
        for item in failures:
            print(f"  {item}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
